apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-snapshot-ingress
  namespace: ai-snapshot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-snapshot-backend
                port:
                  number: 8765
